apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: kubernetes-flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
  replicas: 5 
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: kubernetes-flaskapp
        image: mikehj24/casestudy_part_1
        ports:
        - containerPort: 8095
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-app-service
spec:
  type: NodePort
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
      nodePort: 31121
